### ISSUE TITLE
感谢，不知是否是否为我的异常

### ISSUE THREAD

**Issue by chenjiabin** [guanguans/yii-dingtalk#1]
yii-dingtalk\src\DingTalk.php 

172行  static::$_app = Yii::createObject(Application::class, $this->options);
生成的配置为空
需修改橙
 static::$_app = new Application( $this->options );

**Comment by guanguans** [comment]
@chenjiabin 可能是 Yii 版本导致的问题。方便的话修改一下，提个 `pr` 过来，我这边合并一下。
